### ISSUE TITLE
Opening spec doesn't work for app/lib

### ISSUE THREAD

**Issue by trevorrjohn** [pivotalcommon/vim-config#47]
If I have a class in app/lib and a spec in spec/lib when I use the `A` command (`:A{TVS}` etc) it outputs an error "Can't find file 'app/test/lib/file_name_test.rb' in path". I didn't see the plugin listed in the readme that actually does this searching, but if someone could point me in the right direction I would try to take a look and figure it out.

Thanks

**Comment by trevorrjohn** [comment]
never mind found it in https://github.com/tpope/vim-rails/

**Comment by nertzy** [comment]
You should also read up about https://github.com/tpope/vim-projectionist
